name: Docker CI

on:
  push:        # run on any branch
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanity check
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          docker version
          docker buildx version

      # Optional: log in to GHCR to push images
      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (and optionally push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/virtualdiabeticsclinic:latest
            ghcr.io/${{ github.repository_owner }}/virtualdiabeticsclinic:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

